### ISSUE TITLE
Themeing Icons

### ISSUE THREAD

**Issue by paulatz** [Foundry376/Mailspring-Theme-Starter#12] opened 2021-01-20 21:57 UTC
Hello,
I have started a theme based on the Breeze look from KDE Plasma¹ (Opensuse, Kubuntu, etc.) . I could do most of the reskinning from the starter theme, the Taiga theme (from the git) and the Agapanthus theme (which I found online).

There are some elements which are very difficult to skin. 
1. The sidebar: Some of the id's of the items that hold the folder names and icons are predicatbles, i.e. id="Unread",  others are not human readable, i.e. id="Jm47j8CLKMvTHR8RXMxm2PmDsK86ai3BYnMyb4ow6". I am concerned that these could be computer dependent, and not work properly. But I did not find any other way to identify these items properly.
2. The buttons which are at the bottom of the mail composition window or panel are even harder, and I did not manage to skin most of them. You can see the commented-out failed code in styles/email-frame.less. In the button with a handle (like the reminder button) it is especially difficult to modify the button without changing the handle. Do you have any example were this is done, if it is doable in an official way?

kind regards, and thank you for you great software

[1] https://github.com/paulatz/Mailspring-Theme-Breeze-Light

**Comment by CodeMouse92** [comment] 2021-01-20 22:56
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

As part of this, we've migrated this issue to Discourse:

https://community.getmailspring.com/t/question-about-theming-icons/131

Please join that community and continuing the discussion there! Bonus: if you join and reply to the issue, the moderators can make an effort to reassign the post to you, so you get the credit for it.

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored.

We hope to see you on Discourse soon!

-The Mailspring Team

**Closed as completed by CodeMouse92** 2021-01-20 22:56 UTC
